#include <iostream.h>
//#include <C:\CPP DS Library\Linked List\SinglyLinkedList.hpp>
#include <SinglyLinkedList.hpp>
//using namespace std;

int main()
{
    LinkedList<int> llist;
    // llist.insertAtEnd(15);
    // llist.insertAtEnd(10);
    // llist.insertAtEnd(5);
    // llist.insertAtEnd(20);
    // llist.insertAtEnd(3);
    // llist.insertAtEnd(2);

    // LinkedList<char> llistchar;
    // llistchar.insertAtEnd('f');
    // llistchar.insertAtEnd('g');
    // llistchar.insertAtEnd('z');
    // llistchar.insertAtEnd('a');
    // llistchar.insertAtEnd('b');
    // llistchar.insertAtEnd('u');

    // llistchar.printList();
    llist.printList();
    cout<<"\n";
    // llist.reverse();
    // LinkedList<int> llist1;
    // llist.insertAtEnd(4);
    // llist.insertAtEnd(3);
    // llist.insertAtEnd(2);
    // llist.insertAtEnd(1);
    // llist.merge(llist1);

    // llistchar.sort();
    // llist.sort();

    // llistchar.printList();
    // llist.printList();
    return 0;
}